/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pythontest_MainActivity */

#ifndef _Included_com_example_pythontest_MainActivity
#define _Included_com_example_pythontest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pythontest_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_pythontest_MainActivity_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
